# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cU2cMsqy6IesO8MRZDs6nCdJsidjTvAH

PART 1: Automated Summary (NumPy)
"""

import numpy as np

data = [4.2, 5.1, 3.8, 7.2, 5.5, 6.0]

def summarize_clinic(data):
    mean = np.mean(data)
    std_dev = np.std(data)
    return mean, std_dev

mean, std = summarize_clinic(data)
print("Mean:", mean)
print("Standard Deviation:", std)

data.append(15.0)

mean_new, std_new = summarize_clinic(data)
print("New Mean:", mean_new)
print("New Standard Deviation:", std_new)

"""PART 2: Visualizing the “Compass” (Matplotlib)"""

import matplotlib.pyplot as plt

dosage = np.array([10, 20, 30, 40, 50])
recovery = np.array([1, 2, 3, 4, 5])

plt.scatter(dosage, recovery)
plt.xlabel("Dosage")
plt.ylabel("Recovery")
plt.title("Dosage vs Recovery")
plt.show()

w = 0.1
prediction = w * dosage

plt.scatter(dosage, recovery)
plt.plot(dosage, prediction)
plt.xlabel("Dosage")
plt.ylabel("Recovery")
plt.title("Prediction Line (w = 0.1)")
plt.show()

weights = [0.2, 0.5, 0.8]

plt.scatter(dosage, recovery)

for w in weights:
    plt.plot(dosage, w * dosage, label=f"w = {w}")

plt.xlabel("Dosage")
plt.ylabel("Recovery")
plt.title("Prediction Lines with Different Weights")
plt.legend()
plt.show()